swagger: "2.0"
info:
  version: "0.1.0"
  title: Salas Bibing API
host: localhost:8080
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /salas:
    x-swagger-router-controller: salas
    get:
      description: Devuelve información sore las salas de la Biblioteca
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Room"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /salas/{roomID}:
    x-swagger-router-controller: salas
    get:
      description: Devuelve información sore una sala de la Biblioteca
      operationId: get
      parameters:
        - name: roomID
          in: path
          description: Room number
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Room"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Room:
    required:
      - id
      - turns
    properties:
      id:
        type: integer
      turns:
        type: array
        items:
          $ref: "#/definitions/Turn"
  Turn:
    required:
      - id
      - time
      - available
    properties:
      id:
        type: integer
      time:
        type: string
      available:
        type: boolean

  Error:
    required:
      - message
    properties:
      message:
        type: string
